{% set name = "json-stream-rs-tokenizer" %}
{% set version = "0.4.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/json-stream-rs-tokenizer-{{ version }}.tar.gz
  sha256: 3a49971c6bdb754a5d554b8206ca648c643d32e337fa0816068862acd5900a4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - setuptools
    - wheel
    - setuptools-rust >=1,<2
    - pip
  run:
    - python >=3.7,<4.0

test:
  imports:
    - json_stream_rs_tokenizer
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A faster tokenizer for the json-stream Python library
  home: https://github.com/smheidrich/py-json-stream-rs-tokenizer
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
