{% set name = "json-stream-rs-tokenizer" %}
{% set version = "0.4.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/json-stream-rs-tokenizer-{{ version }}.tar.gz
  sha256: bfeab43c69386a8f78447a7e61951a06a5e434d1f0ee5165b90e725d5f4bc380

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - setuptools
    - wheel
    - setuptools-rust >=1,<2
    - pip
  run:
    - python >=3.7,<4.0

test:
  imports:
    - json_stream_rs_tokenizer
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A faster tokenizer for the json-stream Python library
  home: https://github.com/smheidrich/py-json-stream-rs-tokenizer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
